/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import chat.blocking.ChatClient;
import chat.blocking.ChatServer;
import chat.blocking.ClientSocket;
import chat.blocking.Email;
import com.sun.security.ntlm.Client;
import java.io.IOException;
import java.net.Socket;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Alan
 */
public class TelaCliente extends javax.swing.JFrame implements Runnable{

    public ChatClient chatClient = new ChatClient();;
    
    /**
     * Creates new form TelaCliente
     * @throws java.io.IOException
     * @throws java.lang.InterruptedException
     */
    public TelaCliente() throws IOException, InterruptedException {
        initComponents();
        
    }
    
    
    
    public void DesabilitaEnvioEmail(){
        txtEnderecoDestino.setEnabled(false);
        txtTitulo.setEnabled(false);
        txtAMensagem.setEnabled(false);
        btnEnviar.setEnabled(false);
        btnLimpar.setEnabled(false);
    }
    
    public void LimparCampos(){
        
        txtEnderecoDestino.setText("");
        txtTitulo.setText("");
        txtAMensagem.setText("");
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnEnviar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtEnderecoDestino = new javax.swing.JTextField();
        txtTitulo = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAMensagem = new javax.swing.JTextArea();
        btnLimpar = new javax.swing.JButton();
        btnReceber = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtTituloRecebido = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtAMensagemRecebido = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        txtEnderecoRemetente = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(600, 500));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        btnEnviar.setBackground(new java.awt.Color(141, 196, 235));
        btnEnviar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/send.png"))); // NOI18N
        btnEnviar.setBorderPainted(false);
        btnEnviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnviarActionPerformed(evt);
            }
        });
        getContentPane().add(btnEnviar);
        btnEnviar.setBounds(530, 120, 45, 45);

        jLabel1.setFont(new java.awt.Font("Noto Sans", 1, 12)); // NOI18N
        jLabel1.setText("Assunto");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(60, 50, 100, 25);

        jLabel2.setFont(new java.awt.Font("Noto Sans", 1, 12)); // NOI18N
        jLabel2.setText("Destinatário");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(60, 20, 100, 25);

        jLabel3.setFont(new java.awt.Font("Noto Sans", 1, 12)); // NOI18N
        jLabel3.setText("Mensagem: ");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(60, 80, 100, 25);
        getContentPane().add(txtEnderecoDestino);
        txtEnderecoDestino.setBounds(150, 20, 370, 25);
        getContentPane().add(txtTitulo);
        txtTitulo.setBounds(150, 50, 370, 25);

        txtAMensagem.setColumns(20);
        txtAMensagem.setRows(5);
        jScrollPane1.setViewportView(txtAMensagem);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(150, 80, 370, 130);

        btnLimpar.setBackground(new java.awt.Color(141, 196, 235));
        btnLimpar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/clean.png"))); // NOI18N
        btnLimpar.setBorderPainted(false);
        btnLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparActionPerformed(evt);
            }
        });
        getContentPane().add(btnLimpar);
        btnLimpar.setBounds(530, 20, 45, 45);

        btnReceber.setBackground(new java.awt.Color(141, 196, 235));
        btnReceber.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        btnReceber.setText("Abrir Email");
        btnReceber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReceberActionPerformed(evt);
            }
        });
        getContentPane().add(btnReceber);
        btnReceber.setBounds(480, 240, 100, 25);

        jLabel5.setFont(new java.awt.Font("Noto Sans", 1, 12)); // NOI18N
        jLabel5.setText("Assunto");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(60, 300, 100, 25);

        jLabel6.setFont(new java.awt.Font("Noto Sans", 1, 12)); // NOI18N
        jLabel6.setText("Mensagem: ");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(60, 330, 100, 25);

        txtTituloRecebido.setEditable(false);
        txtTituloRecebido.setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().add(txtTituloRecebido);
        txtTituloRecebido.setBounds(150, 300, 430, 25);

        txtAMensagemRecebido.setEditable(false);
        txtAMensagemRecebido.setColumns(20);
        txtAMensagemRecebido.setRows(5);
        jScrollPane2.setViewportView(txtAMensagemRecebido);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(150, 330, 430, 150);

        jLabel4.setFont(new java.awt.Font("Noto Sans", 1, 12)); // NOI18N
        jLabel4.setText("Remetente");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(60, 270, 100, 25);
        getContentPane().add(txtEnderecoRemetente);
        txtEnderecoRemetente.setBounds(150, 270, 430, 25);

        jLabel8.setBackground(new java.awt.Color(217, 12, 55));
        jLabel8.setFont(new java.awt.Font("Noto Sans", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(31, 103, 166));
        jLabel8.setText("Clique em \"Abrir Email\" Para habilitar a caixa de email");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(150, 240, 330, 25);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/background.png"))); // NOI18N
        jLabel7.setText("background");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(0, 0, 600, 500);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEnviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnviarActionPerformed

        try {

            String enderecoDestino = txtEnderecoDestino.getText();

            String titulo = txtTitulo.getText();

            String mensagem = txtAMensagem.getText();

            chatClient.MessageLoopTela(enderecoDestino, titulo, mensagem, true);

            LimparCampos();

            JOptionPane.showMessageDialog(this, "Email Enviado com Sucesso!", "Informação", JOptionPane.INFORMATION_MESSAGE);

            System.exit(0);

        } catch (IOException | InterruptedException ex) {
            Logger.getLogger(TelaCliente.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_btnEnviarActionPerformed

    private void btnLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparActionPerformed

        LimparCampos();
    }//GEN-LAST:event_btnLimparActionPerformed

    private void btnReceberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReceberActionPerformed
        
        DesabilitaEnvioEmail();
        
        JOptionPane.showMessageDialog(this, "Isto desabilitou o envio de emails", "Caixa Aberta", JOptionPane.INFORMATION_MESSAGE);
            
        //chatClient.MessageLoopTela(null, null, null, false);
        
        new Thread(this).start();
        
        
        
        //new Thread(this).start();
    }//GEN-LAST:event_btnReceberActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed

        
    }//GEN-LAST:event_formWindowClosed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened

        try {
            chatClient.start();
        } catch (IOException | InterruptedException ex) {
            Logger.getLogger(TelaCliente.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]){
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            try {
                new TelaCliente().setVisible(true);
            } catch (IOException | InterruptedException ex) {
                Logger.getLogger(TelaCliente.class.getName()).log(Level.SEVERE, null, ex);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEnviar;
    private javax.swing.JButton btnLimpar;
    private javax.swing.JButton btnReceber;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea txtAMensagem;
    private javax.swing.JTextArea txtAMensagemRecebido;
    private javax.swing.JTextField txtEnderecoDestino;
    private javax.swing.JTextField txtEnderecoRemetente;
    private javax.swing.JTextField txtTitulo;
    private javax.swing.JTextField txtTituloRecebido;
    // End of variables declaration//GEN-END:variables

    @Override
    public void run() {
    
        String msg;
        if (chatClient.clientSocket.getMessage() != null) {
            System.out.println();
            System.out.println("--- EMAIL:RECEBIDO ---");
            
            while ((msg = chatClient.clientSocket.getMessage()) != null) {

                System.out.println(msg);
                
                if(msg.contains("Remetente"))
                {
                    txtEnderecoRemetente.setText(msg.split("Remetente:Remetente:")[1]);
                }
                
                if (msg.contains("Assunto")) 
                {
                    
                    txtTituloRecebido.setText(msg.split("Assunto:Assunto:")[1]);
                    
                }
                
                if (msg.contains("Mensagem")){
                   
                   txtAMensagemRecebido.setText(msg.split("Mensagem:Mensagem:")[1]);
                }
            }
        }
       
        chatClient.clientSocket.close();
        
    }
}
